image:
  repository: ghcr.io/mealie-recipes/mealie:nightly
  tag: v1.0.0  # Replace with latest stable tag

env:
  TZ: America/New_York
  DB_TYPE: sqlite

service:
  main:
    ports:
      http:
        port: 9000

ingress:
  main:
    enabled: true
    hosts:
      - host: mealie.local
        paths:
          - path: /
            pathType: Prefix

persistence:
  config:
    enabled: false
  data:
    enabled: false
