image:
  repository: ghcr.io/hay-kot/mealie
  tag: v1.0.0

env:
  TZ: America/New_York
  DB_TYPE: sqlite

service:
  main:
    ports:
      http:
        enabled: true
        port: 9000
        protocol: TCP
        targetPort: 9000
frontend:
  enabled: false
ingress:
  main:
    enabled: true
    hosts:
      - host: mealie.local
        paths:
          - path: /
            pathType: Prefix
persistence:
  config:
    enabled: false
  data:
    enabled: false
