image:
  repository: hkotel/mealie
  tag: api-v1.0.0beta-2
  pullPolicy: IfNotPresent

frontend:
  image:
    repository: hkotel/mealie
    tag: frontend-v1.0.0beta-2
    pullPolicy: IfNotPresent

env:
  TZ: "America/New_York"

api:
  env:
    TZ: "America/New_York"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: mealie.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 1Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
