image:
  repository: ghcr.io/hay-kot/mealie
  tag: v1.0.0
  pullPolicy: IfNotPresent

env:
  DB_TYPE: sqlite
  TZ: America/New_York

service:
  type: ClusterIP
  port: 80
  targetPort: 9000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: mealie.local
      paths:
        - path: /
          pathType: Prefix
