spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "mealie.fullname" . }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
