env:
  TZ: "America/New_York"
  DB_TYPE: "sqlite"

image:
  repository: hkotel/mealie
  tag: v0.4.3

persistence:
  config:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: "local-path"
